// js/gallery.js
//
// Loads the photo gallery from a local manifest (generated by
// resize-images.js) rather than calling the GitHub API at runtime. The
// GitHub API is rate-limited per visitor IP (60 requests/hour when
// unauthenticated), so pulling the file list from it on every page load
// is both fragile for visitors and slower than serving a static file.

const FOLDER = '../images/compressed';

fetch(`${FOLDER}/manifest.json`)
  .then(res => {
    if (!res.ok) throw new Error(`Failed to load manifest: ${res.status}`);
    return res.json();
  })
  .then(files => {
    const gallery = document.getElementById('gallery');

    files
      .filter(name => /\.(jpe?g|png|webp|gif)$/i.test(name))
      .forEach(name => {
        const img = document.createElement('img');
        img.src = `${FOLDER}/${name}`;
        img.alt = name;
        img.loading = 'lazy';

        img.addEventListener('load', () => {
          img.classList.add('loaded');
        });

        // Open lightbox when a thumbnail is clicked
        img.addEventListener('click', () => openLightbox(img.src, name));

        gallery.appendChild(img);
      });

    gallery.classList.add('loaded');
  })
  .catch(err => {
    document.getElementById('gallery').textContent = 'Could not load photos.';
    console.error(err);
  });


// --- Lightbox setup ---

// Create the lightbox elements once, up front, hidden by default
const lightbox = document.createElement('div');
lightbox.id = 'lightbox';

const lightboxImg = document.createElement('img');
lightbox.appendChild(lightboxImg);

document.body.appendChild(lightbox);

function openLightbox(src, alt) {
  lightboxImg.src = src;
  lightboxImg.alt = alt;
  lightbox.classList.add('active');
}

function closeLightbox() {
  lightbox.classList.remove('active');
}

// Close when clicking anywhere on the overlay
lightbox.addEventListener('click', closeLightbox);

// Close on Escape key
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') closeLightbox();
});